services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: unless-stopped
    # Uncomment and configure the following section when adding PostgreSQL
    # environment:
    #   - DATABASE_URL=postgresql://postgres:postgres@db:5432/connect4
    # depends_on:
    #   - db

  # Uncomment the following section when adding PostgreSQL
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=connect4
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
# Uncomment the following section when adding PostgreSQL
# volumes:
#   postgres_data:
