services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}
      DATABASE_URL: postgresql://postgres:postgres@db:5432/connect4
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - db

  c4ai:
    build:
      context: c4ai
      dockerfile: Dockerfile
    environment:
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}
    ports:
      - '9000:9000'
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connect4
    ports:
      # to connect: `pgcli postgres://postgres:postgres@localhost:54320/connect4`
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']

volumes:
  postgres-data:
