services:
  - type: web
    name: connect4
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    domains:
      - logfire.run
    envVars:
      - key: LOGFIRE_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: connect4-postgres
          property: connectionString

databases:
  - name: connect4-postgres
    plan: basic-1gb
